### ISSUE TITLE
关于代码在windows下train的报错

### ISSUE THREAD

**Issue by JAWILU** [tthinking/YDTR#1]
唐博士您好，您的工作非常完美，我尝试着复现train您的代码，但是我遇到了问题，我是在windows下运行您的train代码，出现以下问题，我将数据集放到目录下也还是同样报错，请问您遇到过这种情况吗？期待您的指点回复，谢谢
![屏幕截图 2023-11-23 152500](https://github.com/tthinking/YDTR/assets/147688830/ab2bb3b8-5da0-49ea-be7b-a0d3a6e187ab)
![屏幕截图 2023-11-23 152545](https://github.com/tthinking/YDTR/assets/147688830/5ae0eb78-bb1f-4c5d-aef3-a56e66f306d9)

**Comment by tthinking** [comment]
看起来应该是你的文件夹路径不对
